# CLI Acceptance Tests that validate & document E2E behavior with the CLI & TestDriver.ai API
name: Acceptance Tests

permissions:
  contents: write
  pull-requests: write
  actions: read
  statuses: write

on:
  # Required checks have to exist in both PRs & Merge Queue:
  # https://github.com/orgs/community/discussions/103114#discussioncomment-8359045
  pull_request:
  # Run in Merge Queue
  merge_group:
    types: [checks_requested]
  # Through the GitHub UI
  workflow_dispatch:
  # Run every day at midnight to ensure CLI -> API works
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish-canary:
    # Only run this job if in the Merge Queue
    if: github.event_name == 'merge_group'
    name: Publish testdriverai@canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Version
        # Unique prerelease version specific to this commit
        # v5.7.40-canary.09e0e4c.0
        run: npm version --no-git-tag-version prerelease --preid=canary.$(git rev-parse --short HEAD)
      - uses: JS-DevTools/npm-publish@v3
        with:
          tag: "canary"
          token: ${{ secrets.NPM_AUTH_TOKEN }}

  gather-test-files:
    # Only run this job if in the Merge Queue
    if: github.event_name == 'merge_group'
    name: Gather Test Files
    runs-on: ubuntu-latest
    outputs:
      test_files: ${{ steps.test_list.outputs.files }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Find all test files
        id: test_list
        run: |
          FILES=$(ls ./testdriver/*.yaml)
          FILENAMES=$(basename -a $FILES)
          FILES_JSON=$(echo "$FILENAMES" | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$FILES_JSON" >> $GITHUB_OUTPUT

  run-tests:
    # Should be automatically skipped outside of Merge Queue
    name: Run Tests
    needs:
      - gather-test-files
      - publish-canary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        test: ${{ fromJson(needs.gather-test-files.outputs.test_files) }}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run TestDriver
        id: testdriver
        uses: testdriverai/action@main
        with:
          version: "canary"
          os: ${{ contains(matrix.os, 'windows') && 'windows' || 'linux' }}
          prerun: |
            exit
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. /run testdriver/${{ matrix.test }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          TD_WEBSITE: "https://testdriver-sandbox.vercel.app"
          TD_VM_RESOLUTION: "1920x1080"

      - name: Write MDX snippets separately
        run: |
          mkdir -p snippets
          FILE_NAME=$(basename "${{ matrix.test }}" .yaml)
          TEST_FILE="testdriver/${FILE_NAME}.yaml"

          EMBED_URL="${{ steps.testdriver.outputs.link }}"
          PARAMS="embed=true&timestamp=90000&playbackRate=5"

          if [[ "$EMBED_URL" == *\?* ]]; then
            EMBED_URL="${EMBED_URL}&${PARAMS}"
          else
            EMBED_URL="${EMBED_URL}?${PARAMS}"
          fi

          # Write iframe MDX
          echo "<iframe src=\"$EMBED_URL\" width=\"100%\" height=\"300\" />" > "snippets/${FILE_NAME}-replay.mdx"

          # Write YAML MDX
          echo '```yaml' > "snippets/${FILE_NAME}-yaml.mdx"
          cat "$TEST_FILE" >> "snippets/${FILE_NAME}-yaml.mdx"
          echo '```' >> "snippets/${FILE_NAME}-yaml.mdx"

      - name: Upload snippets artifact
        uses: actions/upload-artifact@v4
        with:
          name: snippets-${{ matrix.os }}-${{ matrix.test }}
          path: snippets/
          retention-days: 1

  create-snippets-commit:
    # Should be automatically skipped outside of Merge Queue
    name: Commit Snippets
    needs: run-tests
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Check out current branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Download all snippets artifacts
        uses: actions/download-artifact@v4
        with:
          path: docs/snippets/tests
          pattern: snippets-*
          merge-multiple: true

      - name: Commit updated snippets
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Update test snippets [skip ci]"
          add: "docs/snippets/tests"
          new_branch: ${{ github.head_ref }}
          tag_push: "--force-with-lease"
