name: Publish to NPM

on:
    # Instead of a Merge Queue, we'll just run this on main.
  push:
    branches: [main]
  # Through the GitHub UI
  workflow_dispatch:
  # Run every day at midnight to ensure CLI -> API works

jobs:
  tag:
    # Beta until we're stable for @latest
    # https://www.notion.so/Publish-beta-to-NPM-2246adb97c8880678d46de45ace4a0e3?source=copy_link
    name: Publish testdriverai@beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Version
        # Unique prerelease version specific to this commit
        # v5.7.40-canary.09e0e4c.0
        run: npm version --no-git-tag-version prerelease --preid=canary.$(git rev-parse --short HEAD)
      - uses: JS-DevTools/npm-publish@v3
        with:
          tag: "beta"
          token: ${{ secrets.NPM_AUTH_TOKEN }}
