# Ensure that the published `testdriverai` package is installable on multiple version of Node.js across multiple operating systems.
name: Test TestDriverAI Installation

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:
  merge_group:

jobs:
  install-testdriverai:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-latest, windows-latest]
        node-version: ["18", "20", "22"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify `testdriverai` is executable
        run: npx testdriverai@latest -y --help
