name: Test – Env Vars Single-line & Multiline

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      TD_SINGLE_LINE_SECRET: my-super-secret
      TD_MULTILINE_SECRET: |
        -----BEGIN FAKE SSH KEY-----
        line-one-of-key
        line-two-of-key
        line-three-of-key
        -----END FAKE SSH KEY-----

    steps:
      - uses: actions/checkout@v4

      - name: Assert env values are handled correctly on GitHub Runner
        run: |
          echo "::group::GitHub Runner – Environment Check"
          if [[ "$TD_SINGLE_LINE_SECRET" != "my-super-secret" ]]; then
            echo "TD_SINGLE_LINE_SECRET is incorrect: $TD_SINGLE_LINE_SECRET"
            exit 1
          fi

          if [[ "$(echo "$TD_MULTILINE_SECRET" | wc -l)" -lt 3 ]]; then
            echo "TD_MULTILINE_SECRET does not appear multiline"
            exit 1
          fi

          echo "Env values verified on GitHub Runner"
          echo "::endgroup::"

      - name: Run TestDriver
        id: testdriver
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          os: linux
          prerun: |
            Write-Host "# Asserting TD_* env vars"
            if ($env:TD_SINGLE_LINE_SECRET -ne "my-super-secret") {
              Write-Host "TD_SINGLE_LINE_SECRET incorrect: '$($env:TD_SINGLE_LINE_SECRET)'"
              exit 1
            }
            if (-not $env:TD_MULTILINE_SECRET) {
              Write-Host "TD_MULTILINE_SECRET not set"
              exit 1
            }
            $lines = $env:TD_MULTILINE_SECRET.Split("`n").Length
            if ($lines -lt 3) {
              Write-Host "TD_MULTILINE_SECRET is not multiline inside TestDriver (lines: $lines)"
              exit 1
            }
            Write-Host "TD_* env vars validated in PowerShell prerun"
          prompt: |
            Page should contain "TestDriver.ai Sandbox"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TD_WEBSITE: https://testdriver-sandbox.vercel.app
